name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events by only for the main branch
  push:
    branches: [main]
    paths-ignore:
    - "**/coverage.svg"
  pull_request:
    branches: [main]
  # Allow syou to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Disk space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
        echo
    - name: Maximize build disk space
      shell: bash
      run: |
        set -euo pipefail

        echo "Removing unwanted software... "
        echo "  Removing dotnet..."
        sudo rm -rf /usr/share/dotnet
        echo "  Removing android..."
        sudo rm -rf /usr/local/lib/android
        echo "  Removing haskell..."
        sudo rm -rf /opt/ghc
        echo "  Removing CodeQL cache..."
        sudo rm -rf /opt/hostedtoolcache/codeql
        echo "  Removing docker images..."
        sudo docker image prune --all --force
        sudo docker builder prune -a
        echo "... done"
    - name: Disk space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
    - uses: actions/checkout@v6.0.0
    - name: Setup Bazel with Caching
      # Use the setup-bazel action for easy configuration and caching
      uses: bazel-contrib/setup-bazel@0.16.0 # Check for the latest version
      with:
        # Optional: Use Bazelisk for automatic version management
        bazelisk-cache: true
        # Optional: Enable disk cache
        disk-cache: ${{ github.workflow }}
        # Optional: Enable repository cache
        repository-cache: true
    - run: df -h
    - name: Build all targets
      run: bazel build //...
    - name: Run tests
      run: bazel test //...
    - name: Run coverage
      run: bazel coverage --combined_report=lcov //...
    - name: Locate the coverage report
      id: locate_report
      run: |
        COVERAGE_DIR=$(bazel info output_path)/_coverage
        echo "Coverage directory is: $COVERAGE_DIR"
        REPORT_PATH="$COVERAGE_DIR/_coverage_report.dat"
        echo "COVERAGE_REPORT_PATH=$REPORT_PATH" >> $GITHUB_OUTPUT
    - uses: ImBIOS/lcov-coverage-badge@v1.0.1
      with:
        file: ${{ steps.locate_report.outputs.COVERAGE_REPORT_PATH }}
        access_token: ${{ secret.GITHUB_TOKEN }}
        style: flat
        icon_name: googlecloud
        label: 'Coverage'
        label_color: 'ffffff'
        critical: 60
        critical_color: '9c2c9c'
        warning: 75
        warning_color: 'd68f0c'
        success_color: '43ad43'
        message_color: 'ffffff'
