name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events by only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow syou to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Disk space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
        echo
    - name: Maximize build disk space
      shell: bash
      run: |
        set -euo pipefail

        echo "Removing unwanted software... "
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
        echo "... done"
    - name: Disk space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
    - uses: actions/checkout@v6.0.0
    - name: Setup Bazel with Caching
      # Use the setup-bazel action for easy configuration and caching
      uses: bazel-contrib/setup-bazel@0.16.0 # Check for the latest version
      with:
        # Optional: Use Bazelisk for automatic version management
        bazelisk-cache: true
        # Optional: Enable disk cache
        disk-cache: ${{ github.workflow }}
        # Optional: Enable repository cache
        repository-cache: true
    - run: df -h
    - name: Build all targets
      run: bazel build //...
    - name: Run tests
      run: bazel test //...
