name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events by only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow syou to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - run: df -h
    - name: Maximum build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
    - run: df -h
    - uses: actions/checkout@v6.0.0
    - name: Setup Bazel with Caching
      # Use the setup-bazel action for easy configuration and caching
      uses: bazel-contrib/setup-bazel@0.16.0 # Check for the latest version
      with:
        # Optional: Use Bazelisk for automatic version management
        bazelisk-cache: true
        # Optional: Enable disk cache
        disk-cache: ${{ github.workflow }}
        # Optional: Enable repository cache
        repository-cache: true
    - run: df -h
    - name: Build all targets
      run: bazel build //...
    - name: Run tests
      run: bazel test //...
