---
name: CI

# Controls when the workflow will run
on  :
  # Triggers the workflow on push or pull request events by only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allow syou to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.0
    - uses: cachix/install-nix-action@v31.8.4
      with:
        nix_path: nixpkgs=channel:nixos-25.11
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv
    - name: Run a multi-line command in the devenv shell
      shell: devenv shell --profile ci bash -- -e {0}
      run: |
        bazel build //...
    - name: Run a multi-line command in the devenv shell
      shell: devenv shell --profile ci bash -- -e {0}
      run: |
        bazel test //...
