name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events by only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow syou to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - uses: ZenithalHourlyRate/nix-shell-action@v4
        with:
          interpreter: bash
          script: bazel build //...
      - uses: ZenithalHourlyRate/nix-shell-action@v4
        with:
          interpreter: bash
          script: bazel test //...
